name: ValBlock
version: 0.1.0
main: dev.ocean.valblock.Plugin
api-version: 1.21
author: Ocean
description: Valorant recreation in Minecraft

commands:
  valorant:
    description: Main Valorant command
    aliases: [val, vb, valblock]
    usage: /valorant <subcommand>
  
permissions:
  valorant.admin:
    description: Admin permissions for Valorant
    default: op
  valorant.player:
    description: Player permissions for Valorant
    default: true