name: ValBlock
version: 0.1.0
main: dev.ocean.valblock.Plugin
api-version: 1.21
author: Ocean
description: Valorant recreation in Minecraft
depend: [ProtocolLib]
commands:
  valorant:
    description: Main Valorant command
    aliases: [val, vb, valblock]
    usage: /valorant <subcommand>
  vdbg:
    description: ValBlock debugging commands
    usage: /vdbg <subcommand> [arguments]
    permission: valblock.debug
    aliases: [valdebug, valorantdebug]
  
permissions:
  valorant.admin:
    description: Admin permissions for Valorant
    default: op
  valorant.player:
    description: Player permissions for Valorant
    default: true
  valblock.debug:
    description: Access to ValBlock debug commands
    default: op
    children:
      valblock.debug.ability: true
      valblock.debug.cooldown: true
      valblock.debug.charges: true
      valblock.debug.reload: true
      valblock.debug.list: true
      valblock.debug.reset: true
      valblock.debug.info: true